server.port: 8081

# ===============================
# = DATA SOURCE
# ===============================
spring:
    datasource:
        url: jdbc:mysql://localhost:3306/oauth
        username: oauth
        password: ZouNjsMYoll7eGHVWm4xHp75nabi4tqdvQTrUQTD6PVjodXy8UlgIXkpA2G2

        testWhileIdle: true
        validationQuery: SELECT 1

    jpa:
        show-sql: true
        hibernate:
            ddl-auto: update
            naming-strategy: org.hibernate.cfg.ImprovedNamingStrategy
        properties:
            hibernate:
                dialect: org.hibernate.dialect.MySQL5Dialect

oauth.client:
    admin:
        clientId: oauth-provider-admin
        secret: default-secret
    come2help:
        clientId: come2help-web
        secret: secret