# ===============================
# = DATA SOURCE
# ===============================
spring:
    datasource:
        url: jdbc:mysql://localhost:3306/identities?useSSL=false
        username: identities
        password: ZouNjsMYoll7eGHVWm4xHp75nabi4tqdvQTrUQTD6PVjodXy8UlgIXkpA2G2

        testWhileIdle: true
        validationQuery: SELECT 1

        useSSL: false


    jpa:
        show-sql: true
        hibernate:
            ddl-auto: update
            naming-strategy: org.hibernate.cfg.ImprovedNamingStrategy
        properties:
            hibernate:
                dialect: org.hibernate.dialect.MySQL5Dialect